add: zh_tw.json
DM-Earth/Cabricality pull request #64
Opened 2022-10-16 04:15 UTC by EvanHsieh0415

Translator: `YT Mango#4092`, `andree#3110`

2022-10-16 04:45 UTC, JieningYu requested changes
另外，有些地方没有被翻译

2022-10-16 04:45 UTC, JieningYu commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.4.title": "基岩的賞金",
`馈赠`也许更好。

2022-10-16 04:45 UTC, JieningYu commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.5.title": "石電梯",
原文`Andesite Lift`

2022-10-16 04:45 UTC, JieningYu commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"bonus_1a.cabricality.complete.title": "獎金 1A 完成！",
本意为`支线`

2022-10-16 04:45 UTC, JieningYu commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"bonus_2a.cabricality.complete.title": "獎金 2A 完成！",
本意为`支线`

2022-10-16 04:45 UTC, JieningYu commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"bonus_3a.cabricality.complete.title": "獎金 3A 完成！",
本意为`支线`

2022-10-16 05:06 UTC, KrLite requested changes
# 需要更改

- [ ] 章节名称与`简体中文`翻译统一（`繁体中文`中的`纵览`章节是正确的）
- [ ] 翻译所有英文名词
- [ ] 完成未翻译的部分
- [ ] 将`奖金`更改为`支线`
- [ ] 添加*关键词高亮*（格式及颜色请参考`简体中文`翻译）

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_3.cabricality.correction.yellow.title": "&eSpectral Correction &7(Yellow)",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_3.cabricality.correction.green.title": "&aSpectral Correction &7(Green)",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.26.2.title": "&dSpectral Correction &7(Magenta)",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.28.3.content": "最後，最後一個 Crafter 將輻射板切割並纏繞成感應線圈。",
`最後，最後`是否重复？
`Crafter`未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"bonus_3a.cabricality.enderium.title": "Enderium Infused",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.31.2.title": "Ball O' Sand",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_4.cabricality.title": "&f4&r 入盒",
请与简体中文标题统一
第四章`靶向药物`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_2.cabricality.title": "&f2&r 誘人的權宜之計",
请与简体中文标题统一
第二章`初入门道`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_1.cabricality.title": "&f1&r 遠大志向",
请与简体中文标题统一
第一章`扬帆起航`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.15.2.title": "De-Chunkify",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.14.2.content": "將通電的 Certus 石英晶體排放到液體中會產生一種溶液，讓您想起液態紅石。\n&7請注意，混合過程會返回一個惰性石英，準備好使用裝置 14 進行充電。",
名词未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.13.content": "設置一個小循環來為任何在裝置 13-2 中用作催化劑的 Certus Quartz 充電。\n\n這裡可以使用 AE2 的充電器，以及選擇的物品運輸.",
名词未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_2.cabricality.sand.content": "最初，Certus Quartz Seeds 需要沙子來製作。然而，為了完全自動化，在機械工匠的幫助下繞過這個要求可能是值得的。",
名词未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.11.title": "Skystone Infin-mill",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.23.2.title": "Checker Crafters",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_3.cabricality.mob_cage.subtitle": "Alt. 裝置 21 \\& 22",
`Alt.`建议翻译为`备选步骤`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_3.cabricality.title": "&f3&r 宣洩",
请与简体中文翻译统一
第三章`钢铁洪流`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.41.2.title": "Express Circuitry II",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.40.1.content": "使用 Deployers 用矽創建電路底座。所需的 Press 可以位於 Sky Stone Meteors 的中心。",
名词未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.41.1.title": "Express Circuitry I",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.40.1.title": "Circuit Stamper",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_4.cabricality.chapter_4a.task.complete.title": "完成第 4a 章",
`4a`建议翻译为`第四章支线`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.34.3.title": "Pyrolyzer Round II",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.34.2.title": "Pyrolyzer Round I",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.33.1.content": "在準備好進行處理之前，basalz 精華需要進行一些細化。",
名词未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.33.1.title": "Basalz Mill",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_4a.cabricality.title": "↓&r 混沌煉金術",
请与简体中文翻译统一
第四章备选路线`混沌炼金`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.44.1.content": "作為兩個可用數字之一，Threes 可以從未處理的邏輯中轉換。連同八個和可用的運算符，您的計算器將必須創建從 0 到 9 的其餘數字相等\n\n這個鑄造過程很快就會成為一個瓶頸，因為大多數運行計算都取決於這裡生成的數字。確保事情順利進行。",
名词未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_5.cabricality.attire.title": "&9Attire",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.46.content": "對於 Guidance 計算機的計算，我們需要.. 很多這樣的數字。\n\n在讓項目退出計算的邏輯生態系統之前，確保每個數字都離開等量。黃銅隧道可以直接解決這個問題。\n\n現在每個數字都必須通過冶煉廠重新溶解成液化形式。一旦冶煉廠收集到每個數字的 10 個液化物品，它們就會組合成編碼我們的計算機所需的邏輯。一旦積累
“名词未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_4a.cabricality.complete.title": "&3Warp Zone",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_5.cabricality.title": "&f5&r 除以數字",
请与简体中文翻译统一
第五章`意识上传`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.19.title": "Express Sticks",
未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.15.4.content": "將金塊放入您的高溫熔煉設備中。例如，來自 Tinkers' Construct 的熔爐。",
`Tinkers‘ Construct`未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"bonus_1a.cabricality.complete.title": "獎金 1A 完成！",
`1A`建议翻译为`第一章支线`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.8.content": "使用一排 Deployers 將安山岩合金和切割木板組合在一起，完成了您的第一條裝配線。",
名词未翻译

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"bonus_2a.cabricality.complete.title": "獎金 2A 完成！",
`2A`建议翻译为`第二章支线`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"chapter_1.cabricality.title": "&f1&r 遠大志向",
如上，纵览里的章节名称与实际不符。
**请与简体中文章节名称统一**

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"bonus_3a.cabricality.complete.title": "獎金 3A 完成！",
`3A`建议翻译为`第三章支线`

2022-10-16 05:06 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.47.title": "Upcycle Bin",
未翻译

2022-10-25 07:11 UTC, EvanHsieh0415 commented
算了，重新翻譯好了，<del>我找的人好像不太彳亍</del>

2022-11-02 02:26 UTC, EvanHsieh0415 commented
已重新翻譯

2022-11-02 13:53 UTC, JieningYu requested changes, later dismissed

2022-11-02 13:53 UTC, JieningYu commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.2.title"   : "浸出液",
water infuser不宜被翻为“浸出”

2022-11-02 14:10 UTC, EvanHsieh0415 commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.2.title"   : "浸出液",
簡中原文也寫浸出w

2022-11-02 14:10 UTC, KrLite approved these changes
Good 👍

2022-11-02 14:10 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_cn.json
> +	"thanks.cabricality.staff.content" : "&f&lSimibubi&r\n&7原作者&r\n\n&f&lYjn024&r\n&7整合包作者&r\n\n&f&lKrLite&r\n&7翻译/美术/程序&r\n\n&f&lIcedDog\nRogenDong\nSylviBlossom\nNyakoFox&\nMangoJellyPudding\n&7贡献者&r"
请把`&\nMangoJellyPudding`改为`\nMangoJellyPuddimg&r`，不然会出现格式错误。
**繁体中文翻译中的相应格式是正确的。**

2022-11-02 14:10 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.2.title"   : "浸出液",
此为简体中文翻译原文，我认为颇形象。

2022-11-02 14:11 UTC, KrLite commented on config/openloader/resources/cabf-assets/assets/cabricality/lang/zh_tw.json
> +	"contraption.cabricality.2.title"   : "浸出液",
不需要更改，pass

2022-11-02 14:13 UTC, merged

2022-11-02 14:31 UTC, JieningYu commented
😦